from tkinter import *
a=Tk()
a.geometry("1000x1000")
a.title("student registration form")
n=Label(a,text="name",bg="pink",fg="red")
n.grid(row=0,column=0)
e=Entry(a)
e.grid(row=0,column=1)
a1=Label(a,text="password")
a1.grid(row=1,column=0)
e1=Entry(a)
e1.grid(row=1,column=1)
a2=Label(a,text="Branch")
a2.grid(row=2,column=0)
cb=Checkbutton(a,text="cse")
cb.grid(row=3,column=0)
cb2=Checkbutton(a,text="aiml")
cb2.grid(row=4,column=0)
a3=Label(a,text="Programming languages known")
a3.grid(row=5,column=1)
lb=Listbox(a,height=3)
lb.insert(1,"c")
lb.insert(2,"java")
lb.insert(3,"python")
lb.grid(row=6,column=1)
rb=Radiobutton(a,text="male",value=1)
rb.grid(row=7,column=0)
rb2=Radiobutton(a,text="female",value=2)
rb2.grid(row=8,column=0)
b=Button(a,text="submit")
b.grid(row=9,column=3)
a.mainloop()